{% set name = "sphinx-jinja" %}
{% set version = "1.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e6614d986c0289cb85b016c25eb8cb9781ceb841e70bee639c5123f39ad90b38

build:
  noarch: python
  number: 0
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python
    - pbr
  run:
    - python
    - sphinx

test:
  imports:
    - sphinxcontrib.jinja

about:
  home: https://github.com/tardyp/sphinx-jinja
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A sphinx extension to include jinja based templates based documentation into a sphinx doc.
  doc_url: https://github.com/tardyp/sphinx-jinja/blob/master/README.rst
  dev_url: https://github.com/tardyp/sphinx-jinja

extra:
  recipe-maintainers:
    - jonathansick
