{% set name = "sphinx-jinja" %}
{% set version = "2.0.2" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: "c6232b59a894139770be1dc6d0b00a379e4288ce78157904e1f8473dea3e0718"

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv "

requirements:
  host:
    - pip
    - poetry
    - python >=3.6
  run:
    - docutils >=0.16
    - jinja2 >=2.11
    - python >=3.6
    - sphinx >4.2.0

test:
  imports:
    - sphinx_jinja
  commands:
    - pip check
  requires:
    - pip

about:
  home: "https://github.com/tardyp/sphinx-jinja"
  license: "MIT"
  license_family: "MIT"
  license_file: "LICENSE"
  summary: "A sphinx extension to include jinja based templates based documentation into a sphinx doc."
  doc_url: "https://github.com/tardyp/sphinx-jinja/blob/master/README.rst"
  dev_url: "https://github.com/tardyp/sphinx-jinja"

extra:
  recipe-maintainers:
    - awvwgk
    - jonathansick
